version: '3.9'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always

    ports:
      - "3306:3306"

    volumes:
      - ./script/contruct_ecommerce_db.sql:/docker-entrypoint-initdb.d/contruct_ecommerce_db.sql

    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ecommerce