version: '3.9'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always

    ports:
      - 3306:3306

    volumes:
      - ./database-container/config.sql:/docker-entrypoint-initdb.d/config.sql
    
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db_app
